// Uma pista indireta para cada palavra, em todos os cinco níveis.
const hints = {
  FUTEBOL: 'Onze de cada lado, uma bola no gramado e uma torcida que transforma gol em festa.',
  SAMBA: 'O tamborim marca o passo e os pés encontram um balanço que nasceu nas rodas do Rio.',
  PRAIA: 'Areia, mar e uma faixa de sol onde o brasileiro costuma estender a canga.',
  CAFE: 'Pode ser coado, forte ou com leite; quase sempre chega para acordar a conversa.',
  BRASIL: 'Tem cinco letras, começa com B e dá nome ao país que reúne todos estes temas.',
  CHURRASCO: 'A fumaça sobe da churrasqueira enquanto alguém vira a carne e a roda de conversa cresce.',
  NOVELA: 'Capítulos diários, reviravoltas e aquele “no próximo capítulo” que prende a sala inteira.',
  FAROFA: 'Crocante e soltinha, acompanha o feijão e costuma ganhar um lugar ao lado do arroz.',
  PIPOCA: 'O milho pula dentro da panela e vira companhia clássica para filme e sessão de cinema.',
  'FESTA JUNINA': 'Bandeirinhas, quadrilha e milho aparecem quando o arraial toma conta da noite.',
  CAPOEIRA: 'O berimbau acompanha um jogo de esquivas, rasteiras e acrobacias dentro da roda.',
  CARNAVAL: 'A avenida ganha escola de samba, fantasia, bateria e um desfile que atravessa a madrugada.',
  BRIGADEIRO: 'Leite condensado, chocolate e granulado se encontram em um doce pequeno de festa.',
  SERTANEJO: 'Viola, refrão sobre saudade e uma dupla cantando: a música costuma pedir coro.',
  FEIJOADA: 'Feijão preto, carnes e acompanhamentos chegam juntos em uma panela que pede almoço demorado.',
  JABUTICABA: 'A fruta escura nasce agarrada ao tronco, e não nas pontas dos galhos como muita gente imagina.',
  PANTANAL: 'Na cheia, campos inteiros viram espelho; na seca, a vida se concentra perto das águas.',
  'LITERATURA DE CORDEL': 'Versos rimados e ilustrações em madeira contam histórias penduradas em feiras populares.',
  'PAO DE QUEIJO': 'Redondo, assado e com polvilho e queijo: costuma desaparecer ainda quente da cesta.',
  'BUMBA MEU BOI': 'Um boi colorido, música e teatro recontam uma lenda popular nas festas do Maranhão.',
  PARALELEPIPEDO: 'As pedras retangulares formam o calçamento de muitas ruas antigas e rendem uma palavra comprida.',
  'ARARA AZUL': 'A ave de penas azul intenso voa em pares e ficou símbolo da fauna brasileira ameaçada.',
  'LENCOIS MARANHENSES': 'Dunas brancas e lagoas de água da chuva formam um cenário que muda a cada estação.',
  'OURO PRETO': 'Casarões coloniais, igrejas barrocas e ladeiras guardam a história de Minas Gerais.',
  'GUIMARAES ROSA': 'O escritor de Grande Sertão: Veredas inventava palavras para contar o sertão mineiro.'
};
