// Dicas autorais originais preservadas; novas entradas possuem pistas contextuais próprias.
const hints = {
  "FUTEBOL": "Uma partida reúne jogadores, bola, passes, dribles e uma disputa emocionante por gols.",
  "SAMBA": "Seus passos marcados e seu ritmo contagiante costumam animar rodas, festas e celebrações.",
  "PRAIA": "É um lugar onde muitas pessoas aproveitam o sol, a água e momentos de descanso.",
  "CAFE": "Uma bebida quente e aromática costuma acompanhar conversas, estudos e o começo do dia.",
  "BRASIL": "Possui dimensões continentais, grande diversidade cultural e paisagens espalhadas por várias regiões.",
  "CINEMA": "Uma sala escura reúne público, tela grande, histórias e emoções por algumas horas.",
  "BICICLETA": "Duas rodas e o equilíbrio do corpo permitem passeios, exercícios e deslocamentos sem combustível.",
  "MUSICA": "Sons organizados podem despertar lembranças, transmitir sentimentos e acompanhar diferentes momentos da vida.",
  "ESCOLA": "Nesse espaço, pessoas aprendem, convivem, fazem perguntas e desenvolvem novos conhecimentos.",
  "AMIZADE": "A confiança, o carinho e a companhia tornam muitos momentos mais leves e significativos.",
  "FAMILIA": "Pessoas próximas compartilham histórias, cuidados, responsabilidades e lembranças ao longo da vida.",
  "VIAGEM": "Conhecer novos lugares amplia experiências, apresenta culturas diferentes e cria memórias especiais.",
  "SORVETE": "Uma sobremesa gelada pode ter vários sabores e costuma refrescar dias quentes.",
  "JARDIM": "Plantas, flores, cores e cuidados transformam esse espaço em um ambiente agradável.",
  "CHURRASCO": "O aroma da carne assando costuma reunir pessoas em torno de conversa e confraternização.",
  "NOVELA": "Capítulos exibidos regularmente acompanham personagens, conflitos, romances e reviravoltas.",
  "FAROFA": "Esse acompanhamento combina uma textura granulada com temperos e ingredientes variados.",
  "PIPOCA": "Pequenos grãos estouram com o calor e se tornam um lanche clássico para filmes.",
  "FESTA JUNINA": "Bandeirinhas, músicas, danças e comidas típicas deixam essa celebração muito colorida.",
  "PADARIA": "O cheiro de pão fresco costuma receber clientes que procuram lanches e produtos do dia.",
  "MERCADO": "Pessoas percorrem corredores para escolher alimentos, produtos domésticos e itens necessários.",
  "HAMBURGUER": "Um pão macio envolve um recheio central que pode receber queijo, molho e outros acompanhamentos.",
  "COXINHA": "Um salgadinho dourado guarda recheio cremoso dentro de uma massa com formato característico.",
  "RECREIO": "Durante esse intervalo, estudantes conversam, brincam e descansam antes de voltar às atividades.",
  "DOMINGO": "Para muitas pessoas, é um dia associado a descanso, reuniões e refeições tranquilas.",
  "CALCADA": "A faixa junto à rua permite que pedestres caminhem entre casas, lojas e outros espaços.",
  "REDE": "Presa em dois pontos, oferece um balanço confortável para descansar ou passar o tempo.",
  "BATE PAPO": "Uma conversa descontraída permite trocar ideias, novidades e histórias com outras pessoas.",
  "FEIRA": "Barracas, produtos variados e movimento de compradores formam um ambiente cheio de cores e aromas.",
  "CAPOEIRA": "Movimentos corporais, música e esquivas combinam jogo, expressão e tradição em uma roda.",
  "CARNAVAL": "Desfiles, fantasias, música e dança transformam ruas e avenidas em grandes celebrações.",
  "BRIGADEIRO": "Pequenos doces de chocolate, geralmente cobertos com confeitos, aparecem em muitas festas.",
  "SERTANEJO": "Canções sobre sentimentos, cotidiano e relacionamentos conquistam públicos em diferentes regiões.",
  "FEIJOADA": "Uma preparação encorpada costuma ser servida com acompanhamentos e reúne muitas pessoas à mesa.",
  "FREVO": "Passos rápidos, música vibrante e pequenos guarda-chuvas marcam essa manifestação pernambucana.",
  "MARACATU": "Tambores, cortejos e personagens tradicionais formam uma apresentação de forte presença cultural.",
  "BOSSA NOVA": "Um jeito suave de cantar e tocar renovou a música brasileira no século vinte.",
  "PAMONHA": "A massa feita com milho pode ser embrulhada em folhas e preparada doce ou salgada.",
  "ACARAJE": "Bolinhos preparados com feijão-fradinho são fritos e servidos com recheios muito saborosos.",
  "QUADRILHA": "Casais seguem comandos, passos ensaiados e formações durante uma dança tradicional de festa.",
  "ARTESANATO": "Peças produzidas manualmente revelam criatividade, técnicas e características culturais de seus criadores.",
  "RODA DE SAMBA": "Músicos e participantes ficam próximos, cantando e tocando em um encontro descontraído.",
  "FOLIA": "Alegria, música e agitação tomam conta de pessoas reunidas para celebrar.",
  "RAPADURA": "O caldo concentrado de cana transforma-se em um doce firme, tradicional e muito energético.",
  "JABUTICABA": "Seus frutos escuros aparecem presos diretamente ao tronco e têm polpa clara e doce.",
  "PANTANAL": "Em determinadas épocas, grandes áreas ficam alagadas e abrigam uma impressionante variedade de animais.",
  "LITERATURA DE CORDEL": "Pequenos livros, versos rimados e ilustrações populares narram histórias de forma envolvente.",
  "PAO DE QUEIJO": "Pequenas porções assadas têm exterior dourado, interior macio e um aroma irresistível.",
  "BUMBA MEU BOI": "Música, dança, personagens e encenação contam uma história tradicional muito celebrada.",
  "AMAZONIA": "Uma extensa área de floresta e rios influencia o clima e concentra enorme biodiversidade.",
  "CERRADO": "Árvores retorcidas, períodos secos e grande diversidade marcam essa paisagem do interior brasileiro.",
  "CAATINGA": "Plantas adaptadas à pouca água sobrevivem em uma paisagem de clima quente e seco.",
  "IGUACU": "Quedas d’água impressionantes formam um dos cenários naturais mais conhecidos do país.",
  "SACI PERERE": "Um personagem travesso aparece em histórias usando gorro vermelho e realizando brincadeiras inesperadas.",
  "VITORIA REGIA": "Folhas enormes flutuam sobre águas tranquilas e podem sustentar pequenos animais.",
  "MANDIOCA": "Sua raiz pode virar farinha, massa, acompanhamento e muitos preparos presentes na cozinha brasileira.",
  "TUCUPI": "Um caldo amarelo de sabor marcante aparece em preparações tradicionais da região amazônica.",
  "CANGACO": "Grupos armados percorriam o sertão, tornando-se personagens marcantes da história nordestina.",
  "CARIMBO": "Uma superfície gravada recebe tinta e deixa uma marca repetida sobre papel ou outro material.",
  "PARALELEPIPEDO": "Blocos de pedra alinhados podem formar ruas antigas, calçadas e caminhos resistentes.",
  "ARARA AZUL": "Uma ave de plumagem intensa, bico forte e grande porte chama atenção nas paisagens brasileiras.",
  "LENCOIS MARANHENSES": "Dunas claras e lagoas de água doce criam uma paisagem que muda conforme as chuvas.",
  "OURO PRETO": "Igrejas, ladeiras e construções antigas revelam a riqueza histórica de uma cidade mineira.",
  "GUIMARAES ROSA": "Seus textos exploram o sertão, a linguagem e personagens de grande profundidade.",
  "CHAPADA DIAMANTINA": "Cânions, grutas, cachoeiras e trilhas compõem um destino muito procurado por aventureiros.",
  "MATA ATLANTICA": "Mesmo muito transformada, conserva florestas, rios e espécies importantes próximas ao litoral.",
  "MICO LEAO DOURADO": "Um pequeno primata de pelos alaranjados tornou-se símbolo da conservação da fauna brasileira.",
  "CERRADO BRASILEIRO": "Nascentes, campos e árvores adaptadas à estação seca formam uma paisagem de grande importância ambiental.",
  "ALEIJADINHO": "Esculturas e igrejas mineiras estão entre as obras mais lembradas desse artista do período colonial.",
  "OSWALD DE ANDRADE": "Escritor modernista defendeu uma produção artística brasileira mais irreverente e independente.",
  "MACHADO DE ASSIS": "Seus romances e contos observam com ironia as relações e contradições da sociedade.",
  "RIO AMAZONAS": "Um curso de água gigantesco atravessa a floresta e recebe inúmeros afluentes.",
  "PICO DA NEBLINA": "O ponto mais elevado do território nacional costuma ficar envolto por nuvens e nevoeiro.",
  "TIRADENTES": "A figura histórica ficou associada à Inconfidência Mineira e à luta contra o domínio colonial.",
  "VOLEI": "Uma rede divide a quadra enquanto equipes trocam passes sem deixar a bola cair.",
  "BASQUETE": "Passes e saltos ajudam a lançar a bola em um aro acima dos jogadores.",
  "NATACAO": "Braçadas e movimentos coordenados das pernas permitem avançar dentro da água.",
  "TENIS": "Raquetes devolvem uma pequena bola sobre a rede, buscando espaços fora do alcance adversário.",
  "ACAMPAMENTO": "Barracas e refeições ao ar livre acompanham noites passadas longe do conforto de casa.",
  "TELEJORNAL": "Apresentadores e repórteres reúnem os acontecimentos recentes em imagens, entrevistas e informações.",
  "DOCUMENTARIO": "Depoimentos e registros reais ajudam a explorar um assunto com mais profundidade.",
  "DESENHO ANIMADO": "Personagens desenhados ganham movimento e vivem aventuras que podem desafiar as regras da realidade.",
  "SERIE": "Episódios acompanham personagens e conflitos que podem continuar por várias temporadas.",
  "REVEILLON": "Uma contagem regressiva reúne abraços, desejos e comemorações pela chegada de um novo ciclo.",
  "COCADA": "Lascas brancas ou douradas dão textura a pequenos pedaços preparados com açúcar.",
  "QUINDIM": "Sua superfície amarela e brilhante contrasta com uma base delicada que leva coco.",
  "PACOCA": "Amendoim triturado forma pequenos pedaços que se desfazem facilmente ao serem mordidos.",
  "FORRO": "Sanfona, zabumba e triângulo acompanham pares que dançam próximos em festas animadas.",
  "CHORO": "Instrumentistas alternam melodias ágeis e improvisos, muitas vezes reunidos em rodas com cavaquinho e flauta.",
  "PAGODE": "O tantã acompanha refrões descontraídos, frequentemente cantados em coro durante encontros entre amigos.",
  "ABACAXI": "Sua casca áspera esconde uma polpa doce e bastante suculenta.",
  "CAJU": "A parte carnosa acompanha uma castanha externa, muito apreciada depois de torrada.",
  "GOIABA": "A polpa perfumada abriga pequenas sementes e também rende uma pasta firme servida com queijo.",
  "MANGA": "Uma casca colorida envolve polpa suculenta e um caroço grande e achatado.",
  "CURUPIRA": "Seus pés voltados para trás confundem quem tenta seguir suas pegadas pela floresta.",
  "IARA": "Seu canto encantador atrai quem passa perto das águas onde costuma aparecer.",
  "BOITATA": "Um brilho serpenteante percorre os campos nas narrativas de proteção contra incêndios e destruição.",
  "INCONFIDENCIA MINEIRA": "Planos de romper com a Coroa reuniram conspiradores descontentes com cobranças na região das minas.",
  "TUCANO": "Seu bico grande e colorido chama atenção entre os galhos onde procura alimento.",
  "CAPIVARA": "Costuma descansar em grupos perto da água e entra nela com bastante facilidade.",
  "ONCA PINTADA": "A pelagem coberta de rosetas ajuda a esconder um caçador forte entre a vegetação.",
  "CLARICE LISPECTOR": "Em seus textos, pensamentos íntimos transformam situações comuns em descobertas sobre a própria existência.",
  "CECILIA MEIRELES": "Seus versos exploram passagem do tempo, lembranças e sentimentos com delicadeza e forte musicalidade.",
  "DISTRITO FEDERAL": "Abriga a sede do governo nacional e possui organização própria, dividida em regiões administrativas.",
  "ACRE": "Seringais e disputas pela borracha marcaram sua incorporação ao território nacional no início do século passado.",
  "ALAGOAS": "Lagoas costeiras e praias de águas claras convivem com a tradição das rendeiras de filé.",
  "AMAPA": "A linha do Equador atravessa sua sede administrativa, perto da foz de um enorme rio.",
  "AMAZONAS": "Florestas extensas e grandes rios cercam uma metrópole marcada pelo ciclo da borracha.",
  "BAHIA": "A herança afrodescendente aparece fortemente nas celebrações, nos temperos e nos ritmos de seu litoral.",
  "CEARA": "Falésias coloridas e jangadas dividem o litoral com ventos muito procurados por praticantes de esportes aquáticos.",
  "ESPIRITO SANTO": "A tradição das panelas de barro acompanha uma moqueca preparada sem azeite de dendê.",
  "GOIAS": "Cachoeiras e chapadas cercam cidades antigas onde o empadão e o pequi aparecem à mesa.",
  "MARANHAO": "Dunas entremeadas por lagoas e celebrações de um boi enfeitado marcam suas paisagens e tradições.",
  "MATO GROSSO": "Reúne porções de floresta, savana e planície alagável, além de extensas áreas de produção agrícola.",
  "MATO GROSSO DO SUL": "Grutas de água transparente e extensas áreas alagáveis atraem visitantes perto das fronteiras com Paraguai e Bolívia.",
  "MINAS GERAIS": "Montanhas, antigas vilas de mineração e uma mesa farta de queijos fazem parte de sua identidade.",
  "PARA": "O açaí acompanha refeições salgadas, enquanto mercados à beira dos rios oferecem sabores da floresta.",
  "PARAIBA": "Seu litoral abriga o ponto mais oriental das Américas, enquanto o interior celebra grandes festejos populares.",
  "PARANA": "Grandes quedas junto à fronteira e florestas de araucárias fazem parte de suas paisagens.",
  "PERNAMBUCO": "Pontes, bonecos gigantes e passos acelerados com pequenas sombrinhas marcam suas celebrações mais conhecidas.",
  "PIAUI": "Paredões com pinturas rupestres guardam vestígios antigos da presença humana em uma região de clima seco.",
  "RIO DE JANEIRO": "Entre montanhas e mar, guarda lugares associados à antiga corte e a grandes celebrações populares.",
  "RIO GRANDE DO NORTE": "Dunas, salinas e praias ensolaradas acompanham seu litoral, conhecido também pela presença de ventos constantes.",
  "RIO GRANDE DO SUL": "Chimarrão, campos de criação de gado e tradições de fronteira fazem parte de sua identidade.",
  "RONDONIA": "Uma antiga ferrovia ligada à borracha marcou sua ocupação junto à fronteira com a Bolívia.",
  "RORAIMA": "Savanas e montanhas de topo plano compõem paisagens próximas das fronteiras com Venezuela e Guiana.",
  "SANTA CATARINA": "Praias, vales e festas ligadas à imigração europeia atraem visitantes em diferentes épocas do ano.",
  "SAO PAULO": "A expansão do café antecedeu uma intensa industrialização, acompanhada pela chegada de migrantes de muitas origens.",
  "SERGIPE": "O menor em extensão entre seus pares reúne manguezais, praias e cânions próximos de um grande rio.",
  "TOCANTINS": "Criado pela Constituição de 1988, abriga dunas, fervedouros e extensas paisagens de vegetação adaptada à seca.",
  "RIO BRANCO": "Às margens do rio Acre, cresceu ligada à extração da borracha e à vida dos seringais.",
  "MACEIO": "Entre lagoas e mar, suas piscinas naturais e jangadas atraem visitantes para passeios perto da orla.",
  "MACAPA": "Um monumento marca a passagem da linha do Equador, permitindo caminhar entre os hemisférios.",
  "MANAUS": "Um teatro construído durante a riqueza da borracha destaca-se em meio a uma grande metrópole cercada pela floresta.",
  "SALVADOR": "Um elevador liga partes alta e baixa, perto de ruas marcadas pela herança afrodescendente.",
  "FORTALEZA": "O litoral urbano reúne jangadas, humoristas e uma movimentada feira de artesanato à beira do mar.",
  "BRASILIA": "Grandes eixos e edifícios de linhas curvas compõem um projeto urbano planejado para sediar o governo nacional.",
  "VITORIA": "Parte de seu território ocupa uma ilha, cercada por pontes e próxima da tradição das panelas de barro.",
  "GOIANIA": "Planejada no século passado, reúne parques e construções de traços geométricos associados ao estilo art déco.",
  "SAO LUIS": "Casarões revestidos de azulejos dividem espaço com ritmos jamaicanos muito presentes nas festas locais.",
  "CUIABA": "Próxima de chapadas e áreas alagáveis, cresceu com a mineração e mantém tradições como o cururu.",
  "CAMPO GRANDE": "Araras cruzam seus bairros, onde influências de fronteira convivem com pratos trazidos por imigrantes japoneses.",
  "BELO HORIZONTE": "Seu desenho planejado fica cercado por montanhas, com bares e um conjunto arquitetônico à beira de uma lagoa.",
  "BELEM": "Um mercado junto à baía reúne ervas, peixes e sabores, perto de mangueiras que sombreiam as ruas.",
  "JOAO PESSOA": "Próxima do ponto mais oriental das Américas, combina praias urbanas e um centro de construções antigas.",
  "CURITIBA": "Estações em formato de tubo e uma estufa de vidro estão entre suas imagens mais conhecidas.",
  "RECIFE": "Rios e pontes atravessam seus bairros, que ganham multidões durante os festejos de rua.",
  "TERESINA": "Longe do litoral, surgiu planejada entre dois rios e enfrenta tardes de calor intenso.",
  "NATAL": "Dunas e um forte à beira da água fazem parte das paisagens que recebem seus visitantes.",
  "PORTO ALEGRE": "O pôr do sol junto ao Guaíba reúne moradores, frequentemente acompanhados de uma cuia de chimarrão.",
  "PORTO VELHO": "À beira do Madeira, guarda lembranças de uma ferrovia construída para escoar a produção de borracha.",
  "BOA VISTA": "Seu centro foi planejado com ruas em leque, numa área situada acima da linha do Equador.",
  "FLORIANOPOLIS": "Uma ponte suspensa liga o continente à ilha onde praias e antigas comunidades de pescadores atraem visitantes.",
  "ARACAJU": "Planejada junto à foz de um rio, reúne manguezais e uma orla conhecida pelos passeios ao ar livre.",
  "PALMAS": "Planejada após a criação de uma nova unidade federativa, tem avenidas largas e praias junto a um reservatório."
};
