// Uma pista indireta para cada palavra, em todos os cinco níveis.
const hints = {
  FUTEBOL: 'Há dias em que uma conversa sobre ele dura muito mais que o próprio espetáculo.',
  SAMBA: 'Nem todo encontro em roda precisa de uma mesa no meio.',
  PRAIA: 'É um daqueles lugares onde as pegadas não costumam durar muito.',
  CAFE: 'Uma pausa pequena pode ganhar uma conversa comprida na sua companhia.',
  BRASIL: 'Dentro de um mesmo endereço no mapa cabem muitos jeitos de falar e viver.',
  CHURRASCO: 'Quem cuida do preparo costuma trabalhar enquanto os outros colocam o papo em dia.',
  NOVELA: 'Quando parece que tudo vai se resolver, o encontro fica para amanhã.',
  FAROFA: 'Costuma ocupar um cantinho do prato, mas há quem sinta falta dela na mesa inteira.',
  PIPOCA: 'O preparo tem um jeito barulhento de avisar que está acontecendo.',
  'FESTA JUNINA': 'O calendário esfria em parte do país, mas a reunião pede cores e movimento.',
  CAPOEIRA: 'Nesse diálogo, prestar atenção ao movimento do outro vale mais que interrompê-lo.',
  CARNAVAL: 'Durante alguns dias, muita gente troca a roupa de sempre por outra identidade.',
  BRIGADEIRO: 'Em certas comemorações, é difícil esperar o momento oficial para chegar perto dele.',
  SERTANEJO: 'Mesmo longe de onde nasceu, encontra quem cante junto sobre saudade.',
  FEIJOADA: 'Combina mais com uma mesa cheia e uma tarde sem pressa do que com um compromisso corrido.',
  JABUTICABA: 'Quem procura apenas nas pontas dos galhos pode deixar a melhor parte passar.',
  PANTANAL: 'O caminho de uma estação pode virar espelho em outra.',
  'LITERATURA DE CORDEL': 'Uma história pode viajar longe mesmo quando começa em poucas folhas.',
  'PAO DE QUEIJO': 'O tamanho pequeno nem sempre combina com a quantidade que desaparece da cesta.',
  'BUMBA MEU BOI': 'A mesma história ganha roupas, ritmos e sotaques diferentes pelo país.',
  PARALELEPIPEDO: 'Há passeios em que a geometria se faz sentir debaixo dos pés.',
  'ARARA AZUL': 'Na paisagem, uma cor pode chamar atenção antes mesmo de se ouvir uma voz.',
  'LENCOIS MARANHENSES': 'Ali, a chuva ajuda a criar uma paisagem que parece improvável à primeira vista.',
  'OURO PRETO': 'Subir suas ruas é também atravessar camadas de outros séculos.',
  'GUIMARAES ROSA': 'Em suas páginas, o caminho pelo interior também passa por dentro das palavras.'
};
