// Catálogo por fase; cinco palavras são sorteadas por fase em cada partida.
const wordBanks = [
  {
    "name": "Aquecimento",
    "words": [
      [
        "FUTEBOL",
        "Esporte"
      ],
      [
        "SAMBA",
        "Cultura"
      ],
      [
        "PRAIA",
        "Lazer"
      ],
      [
        "CAFE",
        "Comida"
      ],
      [
        "CINEMA",
        "Cultura"
      ],
      [
        "BICICLETA",
        "Lazer"
      ],
      [
        "MUSICA",
        "Cultura"
      ],
      [
        "ESCOLA",
        "Cotidiano"
      ],
      [
        "AMIZADE",
        "Cotidiano"
      ],
      [
        "FAMILIA",
        "Cotidiano"
      ],
      [
        "VIAGEM",
        "Lazer"
      ],
      [
        "SORVETE",
        "Comida"
      ],
      [
        "JARDIM",
        "Natureza"
      ],
      [
        "VOLEI",
        "Esporte"
      ],
      [
        "BASQUETE",
        "Esporte"
      ],
      [
        "NATACAO",
        "Esporte"
      ],
      [
        "TENIS",
        "Esporte"
      ],
      [
        "ACAMPAMENTO",
        "Lazer"
      ]
    ]
  },
  {
    "name": "Brasil cotidiano",
    "words": [
      [
        "CHURRASCO",
        "Comida"
      ],
      [
        "NOVELA",
        "Televisão"
      ],
      [
        "FAROFA",
        "Comida"
      ],
      [
        "PIPOCA",
        "Comida"
      ],
      [
        "FESTA JUNINA",
        "Tradição"
      ],
      [
        "PADARIA",
        "Cotidiano"
      ],
      [
        "MERCADO",
        "Cotidiano"
      ],
      [
        "HAMBURGUER",
        "Comida"
      ],
      [
        "COXINHA",
        "Comida"
      ],
      [
        "RECREIO",
        "Cotidiano"
      ],
      [
        "DOMINGO",
        "Cotidiano"
      ],
      [
        "CALCADA",
        "Cotidiano"
      ],
      [
        "REDE",
        "Lazer"
      ],
      [
        "BATE PAPO",
        "Cotidiano"
      ],
      [
        "FEIRA",
        "Cotidiano"
      ],
      [
        "TELEJORNAL",
        "Televisão"
      ],
      [
        "DOCUMENTARIO",
        "Televisão"
      ],
      [
        "DESENHO ANIMADO",
        "Televisão"
      ],
      [
        "SERIE",
        "Televisão"
      ]
    ]
  },
  {
    "name": "Nossa cultura",
    "words": [
      [
        "CAPOEIRA",
        "Cultura"
      ],
      [
        "CARNAVAL",
        "Tradição"
      ],
      [
        "BRIGADEIRO",
        "Doce"
      ],
      [
        "SERTANEJO",
        "Música"
      ],
      [
        "FEIJOADA",
        "Culinária"
      ],
      [
        "FREVO",
        "Cultura"
      ],
      [
        "MARACATU",
        "Cultura"
      ],
      [
        "BOSSA NOVA",
        "Música"
      ],
      [
        "PAMONHA",
        "Culinária"
      ],
      [
        "ACARAJE",
        "Culinária"
      ],
      [
        "QUADRILHA",
        "Tradição"
      ],
      [
        "ARTESANATO",
        "Cultura"
      ],
      [
        "RODA DE SAMBA",
        "Cultura"
      ],
      [
        "FOLIA",
        "Tradição"
      ],
      [
        "RAPADURA",
        "Doce"
      ],
      [
        "REVEILLON",
        "Tradição"
      ],
      [
        "COCADA",
        "Doce"
      ],
      [
        "QUINDIM",
        "Doce"
      ],
      [
        "PACOCA",
        "Doce"
      ],
      [
        "FORRO",
        "Música"
      ],
      [
        "CHORO",
        "Música"
      ],
      [
        "PAGODE",
        "Música"
      ]
    ]
  },
  {
    "name": "Conhece mesmo?",
    "words": [
      [
        "JABUTICABA",
        "Fruta"
      ],
      [
        "PANTANAL",
        "Geografia"
      ],
      [
        "LITERATURA DE CORDEL",
        "Cultura"
      ],
      [
        "PAO DE QUEIJO",
        "Culinária"
      ],
      [
        "BUMBA MEU BOI",
        "Folclore"
      ],
      [
        "AMAZONIA",
        "Geografia"
      ],
      [
        "CERRADO",
        "Natureza"
      ],
      [
        "CAATINGA",
        "Natureza"
      ],
      [
        "IGUACU",
        "Geografia"
      ],
      [
        "SACI PERERE",
        "Folclore"
      ],
      [
        "VITORIA REGIA",
        "Natureza"
      ],
      [
        "MANDIOCA",
        "Culinária"
      ],
      [
        "TUCUPI",
        "Culinária"
      ],
      [
        "CANGACO",
        "História"
      ],
      [
        "CARIMBO",
        "Cultura"
      ],
      [
        "ACRE",
        "Estados"
      ],
      [
        "ALAGOAS",
        "Estados"
      ],
      [
        "AMAPA",
        "Estados"
      ],
      [
        "AMAZONAS",
        "Estados"
      ],
      [
        "BAHIA",
        "Estados"
      ],
      [
        "CEARA",
        "Estados"
      ],
      [
        "DISTRITO FEDERAL",
        "Geografia"
      ],
      [
        "ESPIRITO SANTO",
        "Estados"
      ],
      [
        "GOIAS",
        "Estados"
      ],
      [
        "MARANHAO",
        "Estados"
      ],
      [
        "MATO GROSSO",
        "Estados"
      ],
      [
        "MATO GROSSO DO SUL",
        "Estados"
      ],
      [
        "MINAS GERAIS",
        "Estados"
      ],
      [
        "PARA",
        "Estados"
      ],
      [
        "PARAIBA",
        "Estados"
      ],
      [
        "PARANA",
        "Estados"
      ],
      [
        "PERNAMBUCO",
        "Estados"
      ],
      [
        "PIAUI",
        "Estados"
      ],
      [
        "RIO DE JANEIRO",
        "Estados"
      ],
      [
        "RIO GRANDE DO NORTE",
        "Estados"
      ],
      [
        "RIO GRANDE DO SUL",
        "Estados"
      ],
      [
        "RONDONIA",
        "Estados"
      ],
      [
        "RORAIMA",
        "Estados"
      ],
      [
        "SANTA CATARINA",
        "Estados"
      ],
      [
        "SAO PAULO",
        "Estados"
      ],
      [
        "SERGIPE",
        "Estados"
      ],
      [
        "TOCANTINS",
        "Estados"
      ],
      [
        "ABACAXI",
        "Fruta"
      ],
      [
        "CAJU",
        "Fruta"
      ],
      [
        "GOIABA",
        "Fruta"
      ],
      [
        "MANGA",
        "Fruta"
      ],
      [
        "CURUPIRA",
        "Folclore"
      ],
      [
        "IARA",
        "Folclore"
      ],
      [
        "BOITATA",
        "Folclore"
      ]
    ]
  },
  {
    "name": "Mestre do Brasil",
    "words": [
      [
        "PARALELEPIPEDO",
        "Cotidiano"
      ],
      [
        "ARARA AZUL",
        "Fauna"
      ],
      [
        "LENCOIS MARANHENSES",
        "Geografia"
      ],
      [
        "OURO PRETO",
        "História"
      ],
      [
        "GUIMARAES ROSA",
        "Literatura"
      ],
      [
        "CHAPADA DIAMANTINA",
        "Geografia"
      ],
      [
        "MATA ATLANTICA",
        "Natureza"
      ],
      [
        "MICO LEAO DOURADO",
        "Fauna"
      ],
      [
        "CERRADO BRASILEIRO",
        "Natureza"
      ],
      [
        "ALEIJADINHO",
        "História"
      ],
      [
        "OSWALD DE ANDRADE",
        "Literatura"
      ],
      [
        "MACHADO DE ASSIS",
        "Literatura"
      ],
      [
        "RIO AMAZONAS",
        "Geografia"
      ],
      [
        "PICO DA NEBLINA",
        "Geografia"
      ],
      [
        "TIRADENTES",
        "História"
      ],
      [
        "RIO BRANCO",
        "Capitais"
      ],
      [
        "MACEIO",
        "Capitais"
      ],
      [
        "MACAPA",
        "Capitais"
      ],
      [
        "MANAUS",
        "Capitais"
      ],
      [
        "SALVADOR",
        "Capitais"
      ],
      [
        "FORTALEZA",
        "Capitais"
      ],
      [
        "BRASILIA",
        "Capitais"
      ],
      [
        "VITORIA",
        "Capitais"
      ],
      [
        "GOIANIA",
        "Capitais"
      ],
      [
        "SAO LUIS",
        "Capitais"
      ],
      [
        "CUIABA",
        "Capitais"
      ],
      [
        "CAMPO GRANDE",
        "Capitais"
      ],
      [
        "BELO HORIZONTE",
        "Capitais"
      ],
      [
        "BELEM",
        "Capitais"
      ],
      [
        "JOAO PESSOA",
        "Capitais"
      ],
      [
        "CURITIBA",
        "Capitais"
      ],
      [
        "RECIFE",
        "Capitais"
      ],
      [
        "TERESINA",
        "Capitais"
      ],
      [
        "RIO DE JANEIRO",
        "Capitais"
      ],
      [
        "NATAL",
        "Capitais"
      ],
      [
        "PORTO ALEGRE",
        "Capitais"
      ],
      [
        "PORTO VELHO",
        "Capitais"
      ],
      [
        "BOA VISTA",
        "Capitais"
      ],
      [
        "FLORIANOPOLIS",
        "Capitais"
      ],
      [
        "SAO PAULO",
        "Capitais"
      ],
      [
        "ARACAJU",
        "Capitais"
      ],
      [
        "PALMAS",
        "Capitais"
      ],
      [
        "INCONFIDENCIA MINEIRA",
        "História"
      ],
      [
        "TUCANO",
        "Fauna"
      ],
      [
        "CAPIVARA",
        "Fauna"
      ],
      [
        "ONCA PINTADA",
        "Fauna"
      ],
      [
        "CLARICE LISPECTOR",
        "Literatura"
      ],
      [
        "CECILIA MEIRELES",
        "Literatura"
      ]
    ]
  }
];
